### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by BigKrisch** [stfnhmplr/homebridge-homee#10]
The following error message appears after the update to version 1.0.0:

[2018-7-21 09:57:17] [homee] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 9. Received 12
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readUInt32BE (internal/buffer.js:198:5)
    at Function.WordArray.fromBuffer (/usr/local/lib/node_modules/homebridge-homee/node_modules/sha512/lib/word-array.js:95:19)
    at subtype.init.finalize (/usr/local/lib/node_modules/homebridge-homee/node_modules/sha512/lib/cryptojs.js:273:33)
    at /usr/local/lib/node_modules/homebridge-homee/node_modules/sha512/lib/cryptojs.js:300:35
    at Homee._getAccessToken (/usr/local/lib/node_modules/homebridge-homee/node_modules/homee-api/homee.js:70:23)
    at Promise (/usr/local/lib/node_modules/homebridge-homee/node_modules/homee-api/homee.js:104:18)
    at new Promise (<anonymous>)
    at Homee.connect (/usr/local/lib/node_modules/homebridge-homee/node_modules/homee-api/homee.js:103:16)
    at new HomeePlatform (/usr/local/lib/node_modules/homebridge-homee/index.js:47:20)
[2018-7-21 09:57:19] [homee] Not connected to homee. Retrying...
[2018-7-21 09:57:21] [Config] Using Form Authentication
[2018-7-21 09:57:21] [homee] Not connected to homee. Retrying...
[2018-7-21 09:57:21] [Config] Console v3.8.5 is listening on port 9999.
[2018-7-21 09:57:23] [homee] Not connected to homee. Retrying...
[2018-7-21 09:57:25] [homee] Not connected to homee. Retrying...
[2018-7-21 09:57:27] [homee] Not connected to homee. Retrying...
[2018-7-21 09:57:29] [homee] Can't connect to homee! Please check that your homee is online and your config is right

**Comment by stfnhmplr** [comment]
Should be fixed with the latest update

**Comment by BigKrisch** [comment]
Perfect. Now it works fine. Many Thanks!
